services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: solstice-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: solstice
      RABBITMQ_DEFAULT_PASS: solstice123